### ISSUE TITLE
Teknologivalg

### ISSUE THREAD

**Issue by sabr5840** [najamoe/AlphaSolutions#7]
Beskrivelse af valg af teknologier herunder feks. JDBC, MySQL, Spring (begrundelse). Her kan man skrive om pros and cons, evt. om andre teknologier man har overvejet og hvorfor det ikke blev til noget. Der skal versionsnumre på (f.eks. IntelliJ 22.2, ikke blot "IntelliJ")

**Comment by najamoe** [comment]
Vi venter til vi er kommet længere ind i projektet for at kunne vurdere de teknologier vi vælger
